SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

adminapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('', views.projecthomepage, name='projecthomepage'),
    path('pagedividecall/', views.pagedividecall, name='pagedividecall'),
    path('printpagelogic/',views.printpagelogic, name='printpagelogic'),
    path('exceptionpagecall/', views.excpetionpagecall, name='exceptionpagecall'),
    path('exceptionpagelogic/', views.exceptionapagelogic, name='exceptionpagelogic'),
    path('randompagecall/', views.randompagecall, name='randompagecall'),
    path('randomlogic/', views.randomlogic, name='randomlogic'),
    path('calculatorlogic/', views.calculatorlogic, name='calculatorlogic'),
    path('add_task/', views.add_task, name='add_task'),
    path('<int:pk>/delete/', views.delete_task, name='delete_task'),
    path('register/', views.register, name='register'),
    path('log_out/', views.log_out, name='log_out'),
    path('user_login/', views.user_login, name='user_login'),
    path('get_time_details/', views.get_time_details, name='get_time_details'),
    path('calculate_future_date/', views.calculate_future_date, name='calculate_future_date'),
    path('AddStudent/', views.add_student, name='AddStudent'),
    path('student_list/', views.student_list, name='student_list'),
    path('generate/', views.upload_file, name='upload_file'),
    path('ContactManager/', views.ContactManager, name='ContactManager'),

]

facultyapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'facultyapp'

urlpatterns = [
    path('faculty_homepage/', views.faculty_homepage, name='faculty_homepage'),
    path('view_student_list/', views.view_student_list, name='view_student_list'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('<int:pk>/delete/', views.delete_task, name='delete'),
    path('add_course/', views.add_course, name='add_course'),
    path('post_marks/',views.post_marks,name='post_marks'),
]

templates/navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>
        body {
            background-image: url('WIN_20231214_10_26_16_Pro.jpg');
            background-size: cover; /* Ensures the image covers the whole background */
            background-position: center; /* Centers the image */
            background-repeat: no-repeat; /* Prevents repeating */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" >
  <div class="container-fluid" style="background-color: DodgerBlue;">
    <a class="navbar-brand" href="{% url 'adminapp:projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:AddStudent' %}">Add Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:student_list' %}">View Student List</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'adminapp:pagedividecall' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:exceptionpagecall' %}">Exception Handling</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:randompagecall' %}">Generate</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:calculatorlogic' %}">Calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:add_task' %}">Add Tasks</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:get_time_details' %}">Time</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:calculate_future_date' %}">Future Date</a></li>
            <li><a class="dropdown-item" href="{% url 'adminapp:upload_file' %}">Generate Chart</a></li>
              <li><a class="dropdown-item" href="{% url 'adminapp:ContactManager' %}">ContactManager</a></li>

          </ul>
        </li>
      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:log_out' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:user_login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

templates/navbar/facultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>
        body {
            background-image: url('WIN_20231214_10_26_16_Pro.jpg');
            background-size: cover; /* Ensures the image covers the whole background */
            background-position: center; /* Centers the image */
            background-repeat: no-repeat; /* Prevents repeating */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" >
  <div class="container-fluid" style="background-color: blue;">
    <a class="navbar-brand" href="{% url 'facultyapp:faculty_homepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
            <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add Course to Student</a>
        </li>
        <li class="nav-item dropdown">
            <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View Students List</a>
        </li>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:add_blog' %}">Blog Site Manager</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:post_marks' %}">Post Marks</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:log_out' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:user_login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

templates/navbar/studentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>
        body {
            background-image: url('WIN_20231214_10_26_16_Pro.jpg');
            background-size: cover; /* Ensures the image covers the whole background */
            background-position: center; /* Centers the image */
            background-repeat: no-repeat; /* Prevents repeating */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" >
  <div class="container-fluid" style="background-color: Green;">
    <a class="navbar-brand" href="#">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Login</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:log_out' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'adminapp:user_login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body%}
{% endblock %}
</body>
</html>